#
# Module manifest for module 'PSDNStoRoute53'
#
# Generated by: leca
#
# Generated on: 2021-11-05
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '3a20e8f9-d6da-4869-baf4-310a6eba9082'

# Author of this module
Author = 'Antoine Lecompte <alecompte@natrix.info>'


# Copyright statement for this module
Copyright = '(c) Antoine Lecompte. All rights Reserved'

# Description of the functionality provided by this module
# Description = ''


# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @("Create-AllZones", "Create-MissingZones", "Export-DNSRecords", "Format-DNSRecords", "Get-AllZones", "Get-ZonesWithWrongDelegationSet", "Import-DNSRecords", "Switch-NameServers", "Verify-Zones", "Wipe-Zones")

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @("Create-AllZones", "Create-MissingZones", "Export-DNSRecords", "Format-DNSRecords", "Get-AllZones", "Get-ZonesWithWrongDelegationSet", "Import-DNSRecords", "Switch-NameServers", "Verify-Zones", "Wipe-Zones")

# Variables to export from this module
VariablesToExport = '*'



# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/alecompte/PSDNStoRoute53'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

